name: Node.js CI

on: [pull_request]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    services:
      postgres:
        image: postgres

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: npm ci
        env:
          HOST: localhost
          DB_PORT: 5432
          DB_PASSWORD: postgres
          DB_USER: postgres
          SECRET: ${{ secrets.SECRET }}
          PORT: 3000
          DB: postgres

      - name: run linter
        run: npm run lint